server {
    listen 8080;
    server_name _;
    root /var/www/html;
    index index.php;

    client_max_body_size 32M;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ ^/index\.php {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_read_timeout 300;
    }

    location ~ ^/(favicon\.ico|sitemap\.xml|robots\.txt|humans\.txt) {
        try_files $uri /index.php?$query_string;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    location ~ ^/storage/app/(uploads/public|media|resources) { try_files $uri 404; }
    location ~ ^/storage/temp/public { try_files $uri 404; }
    location ~ ^/modules/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/plugins/.*/.*/(assets|resources) { try_files $uri 404; }
    location ~ ^/themes/.*/(?:assets|resources) { try_files $uri 404; }
}
